### ISSUE TITLE
Install asks for compiled version, but no releases available?

### ISSUE THREAD

**Issue by brucemoran** [adamallo/PISCA#1]
Hi Adam,

as per instructions, using

`./install.sh /where/is/BEASTv1.8.4/`

results in 

```
PISCA v0.9 Installer

This script has been intended to install the compiled version of PISCA, while it seems that you have downloaded the source code. Please, find the last release of PISCA at https://github.com/adamallo/PISCA/releases/latest
```
but there are no releases available? Can you advise on compiling PISCA from clone or other alternatives? 

Thanks, Bruce.

**Comment by adamallo** [comment]
My bad. I have just published the release of PISCA v1.0. I have also modified the build.xml file so that now you can also compile and install PISCA from its sources. I have documented all this in the README.
